CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER         PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100)  NOT NULL,
    EMAIL         VARCHAR2(200),
    STATE         CHAR(2),
    SIGNUP_DATE   DATE
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID    NUMBER         PRIMARY KEY,
    PRODUCT_NAME  VARCHAR2(200)  NOT NULL,
    CATEGORY      VARCHAR2(100)  NOT NULL,
    PRICE         NUMBER(10,2)   NOT NULL       CHECK (PRICE >= 0)
);

CREATE TABLE ORDERS (
    ORDER_ID      NUMBER         PRIMARY KEY,
    CUSTOMER_ID   NUMBER         NOT NULL,
    ORDER_DATE    DATE           NOT NULL,
    STATUS        VARCHAR2(20)
                  CHECK (STATUS IN ('PENDING', 'SHIPPED', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT FK_ORDER_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER         PRIMARY KEY,
    ORDER_ID      NUMBER         NOT NULL,
    PRODUCT_ID    NUMBER         NOT NULL,
    QUANTITY      NUMBER         NOT NULL       CHECK (QUANTITY > 0),
    UNIT_PRICE    NUMBER(10,2)   NOT NULL       CHECK (UNIT_PRICE >= 0),

    CONSTRAINT FK_ORDER_ITEMS_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT FK_ORDER_ITEMS_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
);