-- =========================================================
-- Oracle Retail Data Pipeline
-- Analysis Queries
-- =========================================================


-- =========================================================
-- Part 1: Basic Queries
-- =========================================================

-- Q1. Completed Orders
-- Retrieve all completed orders, displaying the order ID, customer ID, order date, and status.
-- Sort the results by order date from newest to oldest.
SELECT order_id, customer_id, order_date, status
  FROM orders
 WHERE status = 'COMPLETED'
 ORDER BY order_date desc;

-- Q2. Customers by State
-- Find all customers who live in Florida (FL) or Texas (TX).
-- Display the customer ID, customer name, state, and signup date.
SELECT customer_id, customer_name, state, signup_date
  FROM customers
 WHERE state in ('FL', 'TX');


-- =========================================================
-- Part 2: JOIN Queries
-- =========================================================

-- Q3. Orders with Customer Information
-- Display each order together with the name and state of the customer who placed it.
-- Include the order ID, customer name, state, order date, and order status.
SELECT o.order_id, c.customer_name, c.state, o.order_date, o.status
  FROM customers c 
    JOIN orders o 
      ON c.customer_id = o.customer_id;


-- Q4. Detailed Order Items
-- Display the details of each ordered item.
-- Include the order ID, product name, category, quantity, unit price, and total amount for the item.
-- Total amount should be calculated as:   QUANTITY * UNIT_PRICE
SELECT oi.order_id AS "Order ID",
       pd.product_name AS "Product Name",
       pd.category AS "Category",
       oi.quantity AS "Quantity",
       oi.unit_price AS "Unit Price",
       (oi.quantity * oi.unit_price) AS "Total Amount"
  FROM order_items oi 
        JOIN products pd 
          ON oi.product_id = pd.product_id;


-- Q5. Customers Who Have Never Placed an Order
-- Find customers who have never placed an order.
-- Display the customer ID and customer name.
SELECT cs.customer_id AS "Customer ID",
       cs.customer_name AS "Customer Name"
  FROM customers cs
 WHERE NOT EXISTS (SELECT 1
                     FROM orders od
                    WHERE cs.customer_id = od.customer_id);


-- =========================================================
-- Part 3: Aggregation Queries
-- =========================================================

-- Q6. Number of Orders per Customer
-- Calculate the number of orders placed by each customer.
-- Display the customer ID, customer name, and order count.
-- Sort the results from the highest order count to the lowest.
SELECT cs.customer_id AS "Customer ID",
       cs.customer_name AS "Customer Name",
       count(od.order_id) AS "Order Count"
  FROM customers cs
        LEFT JOIN orders od
          ON cs.customer_id = od.customer_id
GROUP BY cs.customer_id, cs.customer_name
ORDER BY COUNT(od.order_id) DESC;


-- Q7. Revenue by Product
-- Calculate the total sales quantity and total revenue generated by each product.
-- Only completed orders should be included.
-- Revenue should be calculated as:
--     QUANTITY * UNIT_PRICE
SELECT pd.product_id AS "Product ID",
       pd.product_name AS "Product Name",
       SUM(oi.quantity) AS "Total Sales Quantity",
       SUM(oi.quantity * oi.unit_price) AS "Revenue"
  FROM order_items oi
    JOIN orders od
      ON oi.order_id = od.order_id
    JOIN products pd
      ON oi.product_id = pd.product_id
 WHERE od.status = 'COMPLETED'
 GROUP BY pd.product_id, pd.product_name;
 

-- Q8. Revenue by Product Category
-- Calculate the total revenue generated by each product category using COMPLETED orders only.
-- Sort the categories from highest revenue to lowest.
SELECT pd.category AS "Category",
       SUM(oi.quantity * oi.unit_price) AS "Total Revenue"
  FROM products pd
      JOIN order_items oi
        ON pd.product_id = oi.product_id
      JOIN orders od
        ON oi.order_id = od.order_id
 WHERE od.status = 'COMPLETED'
 GROUP BY pd.category
 ORDER BY SUM(oi.quantity * oi.unit_price) DESC;


-- =========================================================
-- Part 4: HAVING and CASE
-- =========================================================

-- Q9. Repeat Customers
-- Find customers who have placed at least three orders.
-- Display the customer ID, customer name, and order count.
SELECT cs.customer_id AS "Customer ID",
       cs.customer_name AS "Customer Name",
       COUNT(od.order_id) AS "Order Count"
  FROM customers cs
      JOIN orders od
        ON cs.customer_id = od.customer_id
 GROUP BY cs.customer_id, cs.customer_name
HAVING COUNT(od.order_id) >= 3;



-- Q10. Customer Spending Classification
-- Calculate each customer's total spending using completed orders only.
-- Classify each customer into one of the following groups:
--
-- HIGH VALUE   : $700 or more
-- MEDIUM VALUE : $300 to $699.99
-- LOW VALUE    : less than $300
--
-- Display the customer name, total spending, and customer category.
WITH calculated_list AS (
    SELECT cs.customer_name AS customer_name,
           SUM(oi.quantity*oi.unit_price) AS total_spending
      FROM customers cs
            JOIN orders od 
              ON cs.customer_id = od.customer_id
            JOIN order_items oi 
              ON od.order_id = oi.order_id
     WHERE od.status = 'COMPLETED'
    GROUP BY cs.customer_name
)
SELECT customer_name,
       total_spending,
       CASE
            WHEN total_spending >= 700 THEN 'HIGH VALUE'
            WHEN total_spending >= 300 THEN 'MEDIUM VALUE'
            ELSE 'LOW VALUE'
        END AS customer_category
  FROM calculated_list;


-- =========================================================
-- Part 5: Date Analysis
-- =========================================================

-- Q11. Monthly Revenue
-- Calculate total revenue for each month using completed orders only.
-- Display the year-month and total revenue.
-- Sort the results chronologically.
SELECT TO_CHAR(od.order_date, 'YYYY-MM') AS year_month,        
       SUM((oi.unit_price * oi.quantity)) AS total_revenue
  FROM orders od
        JOIN order_items oi
          ON od.order_id = oi.order_id
 WHERE od.status = 'COMPLETED'
GROUP BY to_char(od.order_date, 'YYYY-MM')
ORDER BY year_month;


-- Q12. Monthly Order Count by Status
-- Calculate the number of orders placed during each month, separated by order status.
-- Display the year-month, order status, and order count.
-- Sort the results chronologically.
SELECT TO_CHAR(order_date, 'YYYY-MM') year_month,
       status,
       COUNT(*) AS order_count
  FROM orders
GROUP BY TO_CHAR(order_date, 'YYYY-MM'), status
ORDER BY year_month;


-- =========================================================
-- Part 6: Subqueries and CTEs
-- =========================================================

-- Q13. Products with Above-Average Revenue
-- Calculate the total revenue generated by each product using completed orders only.
-- Then calculate the average of these product-level total revenues.
-- Find products whose total revenue is greater than that average.
-- Display the product ID, product name, and total revenue.
WITH rev_per_prod AS (
    SELECT pd.product_id,
           pd.product_name,
           SUM(oi.quantity * oi.unit_price) AS total_revenue
      FROM products pd
          JOIN order_items oi
            ON pd.product_id = oi.product_id
          JOIN orders od
            ON oi.order_id = od.order_id
     WHERE od.status = 'COMPLETED'
     GROUP BY pd.product_id, pd.product_name
)
SELECT product_id,
       product_name,
       total_revenue
  FROM rev_per_prod
 WHERE total_revenue > (SELECT AVG(total_revenue)
                          FROM rev_per_prod);



-- Q14. Customer with the Highest Total Spending
-- Find the customer who spent the most money on completed orders.
-- Display the customer ID, customer name, and total spending.
WITH total_spend AS (
    SELECT cs.customer_id AS id,
           cs.customer_name AS name,
           SUM(oi.quantity * oi.unit_price) AS summed_spend
      FROM customers cs
          JOIN orders od
            ON cs.customer_id = od.customer_id
          JOIN order_items oi
            ON oi.order_id = od.order_id
     WHERE od.status = 'COMPLETED'
     GROUP BY cs.customer_id, cs.customer_name
)
SELECT *
  FROM total_spend
ORDER BY summed_spend DESC
FETCH FIRST 1 ROW ONLY;


-- =========================================================
-- Part 7: Window Functions
-- =========================================================

-- Q15. Product Revenue Ranking
-- Rank all products based on their total revenue from completed orders.
-- Display the product name, category, total revenue, and revenue rank.
SELECT pd.product_name,
       pd.category,
       SUM(oi.quantity * oi.unit_price) AS total_revenue,
       RANK() OVER (
           ORDER BY SUM(oi.quantity * oi.unit_price) DESC
       ) AS revenue_rank
  FROM products pd
      JOIN order_items oi
        ON pd.product_id = oi.product_id
      JOIN orders od
        ON oi.order_id = od.order_id
 WHERE od.status = 'COMPLETED'
 GROUP BY pd.product_name, pd.category
 ORDER BY revenue_rank;


-- Q16. Product Ranking Within Each Category
-- Rank products by total revenue within their own product category using completed orders only.
-- Display the category, product name, total revenue, and rank within the category.
WITH grouped_by_category AS (
    SELECT pd.category,
           pd.product_name,
           SUM(oi.quantity * oi.unit_price) AS rev
      FROM products pd
          JOIN order_items oi
            ON pd.product_id = oi.product_id
          JOIN orders od
            ON oi.order_id = od.order_id
     WHERE od.status = 'COMPLETED'
     GROUP BY pd.category,
              pd.product_name
)
SELECT gc.category,
       gc.product_name,
       gc.rev AS total_revenue,
       RANK() OVER ( PARTITION BY gc.category
                     ORDER BY gc.rev DESC
                   ) AS "Rank By Category"
  FROM grouped_by_category gc
ORDER BY gc.category, "Rank By Category";


-- Q17. Previous Month Revenue Comparison
-- Calculate monthly revenue using completed orders.
-- Compare each month's revenue with the previous month's revenue.
-- Display:
--   year-month
--   current month revenue
--   previous month revenue
--   revenue difference
WITH monthly_revenue AS (
    SELECT
        TO_CHAR(od.order_date, 'YYYY-MM') AS year_month,
        SUM(oi.quantity * oi.unit_price) AS current_revenue
    FROM orders od
        JOIN order_items oi
          ON od.order_id = oi.order_id
    WHERE od.status = 'COMPLETED'
    GROUP BY TO_CHAR(od.order_date, 'YYYY-MM')
)
SELECT
    year_month,
    current_revenue,
    LAG(current_revenue) OVER (ORDER BY year_month) AS previous_revenue,
    current_revenue - LAG(current_revenue) OVER (ORDER BY year_month) AS revenue_difference
FROM monthly_revenue
ORDER BY year_month;


-- =========================================================
-- Part 8: Business Analysis
-- =========================================================

-- Q18. Discounted Sales
-- Find order items where the actual selling price (ORDER_ITEMS.UNIT_PRICE) was lower than the
-- listed product price (PRODUCTS.PRICE).
-- Display:
--   order ID
--   product name
--   listed price
--   selling price
--   discount amount per unit
SELECT oi.order_id AS "Order ID",
       pd.product_name AS "Product Name",
       pd.price AS "Listed Price",
       oi.unit_price AS "Selling Price",
       pd.price - oi.unit_price AS "Discount Amount Per Unit"
  FROM products pd
      JOIN order_items oi
        ON oi.product_id = pd.product_id
 WHERE oi.unit_price < pd.price;


-- Q19. Revenue by State
-- Calculate total revenue generated by customers in each state.
-- Only completed orders should be included.
-- Display the state and total revenue.
-- Sort the results from highest revenue to lowest.
SELECT cs.state AS "State",
       SUM(oi.quantity * oi.unit_price) AS "Total Revenue"
  FROM customers cs
      JOIN orders od
        ON od.customer_id = cs.customer_id
      JOIN order_items oi
        ON oi.order_id = od.order_id
 WHERE od.status = 'COMPLETED'
GROUP BY cs.state
ORDER BY SUM(oi.quantity * oi.unit_price) DESC;


-- Q20. Top Customer in Each State
-- Find the customer with the highest total spending in each state using completed orders only.
-- Display:
--   state
--   customer ID
--   customer name
--   total spending
WITH state_rev AS (
    SELECT pre_pr.*,
           ROW_NUMBER() OVER (PARTITION BY pre_pr.state ORDER BY pre_pr.rev DESC) rn
      FROM (
            SELECT cs.state,
                   cs.customer_id,
                   cs.customer_name,
                   SUM( oi.quantity * oi.unit_price ) rev
              FROM customers cs
                    JOIN orders od
                      ON od.customer_id = cs.customer_id
                    JOIN order_items oi
                      ON oi.order_id = od.order_id
             WHERE od.status = 'COMPLETED'
            GROUP BY cs.state, cs.customer_id, cs.customer_name
           ) pre_pr
)
SELECT state AS "state",
       customer_id AS "customer ID",
       customer_name AS "customer name",
       rev as "total spending"
  FROM state_rev 
WHERE rn = 1;